version: '3.8'
services:
  test-web-site-1:
    image: "node:14-alpine"
    user: "node"
    working_dir: "/home/node/app"
    volumes:
      - ./server.js:/home/node/app/server.js
      - ./node_modules/:/home/node/app/node_modules/
    ports:
      - "8001:3000"
    command: "node server.js"

  gridc-tunnel-to-web-site-1:
    image: gridlastic/docker-gridc
    environment:
      GRIDC_DEBUG: 1
      GRIDC_ENDPOINT_SUBDOMAIN: ${GRIDC_ENDPOINT_SUBDOMAIN}
      GRIDC_USERNAME: ${GRIDC_USERNAME}
      GRIDC_ACCESS_KEY: ${GRIDC_ACCESS_KEY}
      GRIDC_PROTOCOL: ${GRIDC_PROTOCOL}
      GRIDC_SUBDOMAIN: ${GRIDC_CONFIG_SUBDOMAIN_UUID_PREFIX}-host
      GRIDC_ADDR_DOMAIN: test-web-site-1
      GRIDC_ADDR_PORT: 3000
    depends_on:
      - test-web-site-1
